server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          my-server:
            provider: my-provider
            client-id: tutorialspoint
            client-secret: my-secret-key
            authorization-grant-type: client_credentials
            scope: message.read,message.write
        provider:
          my-provider:
            authorization-uri: http://localhost:8081/oauth/authorize
            token-uri: http://localhost:8081/oauth/token

messages:
  base-uri: http://localhost:8081