server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: tutorialspoint
      clientSecret: my-secret-key
      accessTokenUri: http://localhost:8081/oauth/token